version: '3.6'

networks:
  ipvlan0:
    driver: ipvlan
    driver_opts:
      parent: ens192

services:
  telegraf:
    image: telegraf:1.27-alpine
    container_name: telegraf
    restart: always
    volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    #ports:
    #- '8125:8125'
    networks:
      ipvlan0:
        ipv4_address: 172.29.31.2

  influxdb:
    image: influxdb:2.7-alpine
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    networks:
      ipvlan0:
        ipv4_address: 172.29.31.3
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-server
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    networks:
      ipvlan0:
        ipv4_address: 172.29.31.4
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data: {}
  influxdb_data: {}